# `sudo:false` for faster builds.
sudo: false
language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"

stages:
  - test

jobs:
  include:
    - stage: test
      script: npm run test
      after_success: codecov

notifications:
  email: false
  webhooks: https://www.travisbuddy.com/
  on_success: never
